#!/bin/bash

CHMOD="a-w"
if [ "$1" == "-w" ]; then
	CHMOD="a+w"
	shift 1
fi

for f in $*
do
	if [ $(expr $f : '.*~[0-9][0-9][0-9]' ) -eq 0 ]
	then
		ORIGINAL=$(realpath $f)
		N=0
		COPY=$(printf '%s~%3.3d' "$ORIGINAL" "$N")
		while [ -e "$COPY" ]
		do
			N=$(expr $N + 1)
			COPY=$(printf '%s~%3.3d' "$ORIGINAL" "$N")
		done
		if [ -d "$ORIGINAL" ]
		then
			tar -C "$(dirname $ORIGINAL)" -zcf "$COPY" "$(basename $ORIGINAL)"
		else
			cp -p "$ORIGINAL" "$COPY"
		fi
		chmod $CHMOD "$COPY"
		echo "$COPY"
	fi
done
