#!/bin/bash

if [ $# -eq 0 -o "$1" == "--help" ]
then
	echo "usage: $(basename $0) [ options ] pid"
	exit 1
fi

PID=$1
shift 1

JMAP=$JAVA_HOME/bin/jmap

if [ -r /proc/$PID/cmdline ]
then
	BIN_HOME=$(dirname $(strings /proc/$PID/cmdline | head -1))
	if [ $BIN_HOME != "." ]
	then
		JMAP=$BIN_HOME/jmap
	fi
fi

if [ $(id -u) -eq 0 ]
then
	sudo -u tomcat $JMAP -dump:file=$PID.jmap "$@" $PID
else
	$JMAP -dump:file=$PID.jmap "$@" $PID
fi

# END
