#!/bin/bash

DIR="."
if [ -d "$1" ]; then
	DIR=$(realpath $1)
	shift 1
fi

FIND="find $DIR -type f -and ( -name $1" 
shift 1
for f in $*; do
   FIND="$FIND -or -name $f" 
done
FIND="$FIND )"

vi $($FIND)

# END
